# Generated by Django 2.2.12 on 2020-05-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTestList',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('url_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('date', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('cpu', models.FloatField(null=True)),
                ('memory', models.FloatField(null=True)),
                ('disk', models.FloatField(null=True)),
                ('network', models.FloatField(null=True)),
                ('network_recv', models.FloatField(null=True)),
                ('network_sent', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('server_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PingResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ping_result', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('server_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.ServerList')),
            ],
        ),
        migrations.CreateModel(
            name='iPerfTestResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_Mbps', models.FloatField()),
                ('received_Mbps', models.FloatField()),
                ('retransmits', models.FloatField()),
                ('tcp_mss_default', models.FloatField()),
                ('server_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.ServerList')),
            ],
        ),
        migrations.CreateModel(
            name='HTMLTestResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dns_query', models.FloatField(null=True)),
                ('tcp_connection', models.FloatField(null=True)),
                ('request', models.FloatField(null=True)),
                ('dom_parse', models.FloatField(null=True)),
                ('blank_screen', models.FloatField(null=True)),
                ('onload', models.FloatField(null=True)),
                ('dom_ready', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.HTMLTestList')),
            ],
        ),
    ]
