# Generated by Django 2.2.12 on 2020-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iperftestresults',
            name='retransmits',
            field=models.FloatField(null=True),
        ),
    ]
