# Generated by Django 2.2.12 on 2020-05-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0004_auto_20200508_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfoThreshold',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('cpu_threshold', models.FloatField()),
                ('memory_threshold', models.FloatField()),
                ('disk_threshold', models.FloatField()),
                ('bandwidth_threshold', models.FloatField()),
                ('HTML_open_time_threshold', models.FloatField()),
                ('backend_management_system_open_time_threshold', models.FloatField()),
                ('microservices_exec_time_threshold', models.FloatField()),
                ('tcp_sent_Mbps_threshold', models.FloatField()),
                ('tcp_received_Mbps_threshold', models.FloatField()),
            ],
        ),
    ]
