# Generated by Django 2.2.12 on 2020-05-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0005_serverinfothreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
