# Generated by Django 2.2.12 on 2020-05-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0006_auto_20200509_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfothreshold',
            name='ping_threshold',
            field=models.FloatField(default=1),
        ),
    ]
