# Generated by Django 2.2.12 on 2020-05-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0007_serverinfothreshold_ping_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperftestresults',
            name='error',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='iperftestresults',
            name='received_Mbps',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='iperftestresults',
            name='sent_Mbps',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='iperftestresults',
            name='tcp_mss_default',
            field=models.FloatField(null=True),
        ),
    ]
